import React from 'react';
import { Lightbulb, AlertTriangle, TrendingUp, CheckCircle2, Clock, DollarSign, Target, Info, Shield, Home, FileText } from 'lucide-react';

interface FundingLLMInsightsProps {
  insights: {
    generated_at: string;
    model: string;
    method: string;
    insights: {
      overall_explanation: {
        summary: string;
        key_findings: string[];
        confidence_level: 'high' | 'medium' | 'moderate';
      };
      chc_explanation: {
        what_it_means: string;
        eligibility_factors: string[];
        next_steps?: string[];
        important_notes?: string[];
      };
      la_funding_explanation: {
        what_it_means: string;
        means_test_summary: string;
        contribution_explanation?: string;
        tips?: string[];
      };
      dpa_explanation: {
        what_it_means: string;
        property_status: string;
        benefits?: string[];
        considerations?: string[];
      };
      expert_advice: {
        funding_strategy: string;
        maximizing_eligibility?: string[];
        common_mistakes?: string[];
        when_to_reassess?: string;
      };
      actionable_next_steps: Array<{
        step: string;
        priority: 'high' | 'medium' | 'low';
        timeline: string;
        details?: string;
      }>;
    };
  };
}

export default function FundingLLMInsights({ insights }: FundingLLMInsightsProps) {
  console.log('🔍 [FundingLLMInsights] Component mounted with insights:', {
    hasInsights: !!insights,
    insightsKeys: insights ? Object.keys(insights) : [],
    model: insights?.model,
  });
  
  const { overall_explanation, chc_explanation, la_funding_explanation, dpa_explanation, expert_advice, actionable_next_steps } = insights.insights;

  const getConfidenceColor = (level: string) => {
    switch (level) {
      case 'high':
        return 'text-green-600 bg-green-50';
      case 'medium':
        return 'text-blue-600 bg-blue-50';
      default:
        return 'text-yellow-600 bg-yellow-50';
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'high':
        return 'text-red-600 bg-red-50 border-red-200';
      case 'medium':
        return 'text-yellow-600 bg-yellow-50 border-yellow-200';
      default:
        return 'text-blue-600 bg-blue-50 border-blue-200';
    }
  };

  return (
    <div className="mt-8 space-y-6">
      {/* Header */}
      <div className="bg-gradient-to-r from-purple-50 to-indigo-50 rounded-lg p-6 border border-purple-200">
        <div className="flex items-center gap-3 mb-2">
          <Lightbulb className="w-6 h-6 text-purple-600" />
          <h3 className="text-2xl font-bold text-gray-900">Expert Insights & Explanations</h3>
        </div>
        <p className="text-sm text-gray-600">
          AI-powered analysis by our UK care funding specialist to help you understand your funding results
        </p>
        <div className="mt-3 flex items-center gap-2 text-xs text-gray-500">
          <Info className="w-4 h-4" />
          <span>Generated by {insights.model} • {new Date(insights.generated_at).toLocaleString()}</span>
        </div>
      </div>

      {/* Overall Explanation */}
      <div className="bg-white rounded-lg p-6 border border-gray-200 shadow-sm">
        <h4 className="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
          <Info className="w-5 h-5 text-blue-600" />
          What Your Results Mean
        </h4>
        <p className="text-gray-700 mb-4 leading-relaxed">{overall_explanation.summary}</p>
        
        <div className="mb-4">
          <div className="flex items-center gap-2 mb-2">
            <span className="text-sm font-semibold text-gray-700">Key Findings:</span>
            <span className={`px-2 py-1 rounded text-xs font-medium ${getConfidenceColor(overall_explanation.confidence_level)}`}>
              {overall_explanation.confidence_level.toUpperCase()} Confidence
            </span>
          </div>
          <ul className="space-y-2">
            {overall_explanation.key_findings.map((finding, idx) => (
              <li key={idx} className="flex items-start gap-2 text-gray-700">
                <CheckCircle2 className="w-4 h-4 text-green-600 flex-shrink-0 mt-0.5" />
                <span>{finding}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* CHC Explanation */}
      <div className="bg-white rounded-lg p-6 border border-gray-200 shadow-sm">
        <h4 className="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
          <Shield className="w-5 h-5 text-blue-600" />
          NHS Continuing Healthcare (CHC)
        </h4>
        <p className="text-gray-700 mb-4">{chc_explanation.what_it_means}</p>
        
        <div className="mb-4">
          <div className="text-sm font-semibold text-gray-700 mb-2">Eligibility Factors:</div>
          <ul className="space-y-2">
            {chc_explanation.eligibility_factors.map((factor, idx) => (
              <li key={idx} className="flex items-start gap-2 text-sm text-gray-700">
                <TrendingUp className="w-4 h-4 text-blue-600 flex-shrink-0 mt-0.5" />
                <span>{factor}</span>
              </li>
            ))}
          </ul>
        </div>
        
        {chc_explanation.next_steps && chc_explanation.next_steps.length > 0 && (
          <div className="mb-4">
            <div className="text-sm font-semibold text-gray-700 mb-2">Next Steps:</div>
            <ul className="space-y-2">
              {chc_explanation.next_steps.map((step, idx) => (
                <li key={idx} className="flex items-start gap-2 text-sm text-gray-700">
                  <Target className="w-4 h-4 text-green-600 flex-shrink-0 mt-0.5" />
                  <span>{step}</span>
                </li>
              ))}
            </ul>
          </div>
        )}
        
        {chc_explanation.important_notes && chc_explanation.important_notes.length > 0 && (
          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
            <div className="text-sm font-semibold text-yellow-800 mb-2">Important Notes:</div>
            <ul className="space-y-1">
              {chc_explanation.important_notes.map((note, idx) => (
                <li key={idx} className="text-sm text-yellow-700">• {note}</li>
              ))}
            </ul>
          </div>
        )}
      </div>

      {/* LA Funding Explanation */}
      <div className="bg-white rounded-lg p-6 border border-gray-200 shadow-sm">
        <h4 className="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
          <DollarSign className="w-5 h-5 text-green-600" />
          Local Authority Funding
        </h4>
        <p className="text-gray-700 mb-3">{la_funding_explanation.what_it_means}</p>
        <p className="text-gray-700 mb-4 font-medium">{la_funding_explanation.means_test_summary}</p>
        
        {la_funding_explanation.contribution_explanation && (
          <div className="mb-4 p-3 bg-blue-50 border border-blue-200 rounded-lg">
            <p className="text-sm text-gray-700">{la_funding_explanation.contribution_explanation}</p>
          </div>
        )}
        
        {la_funding_explanation.tips && la_funding_explanation.tips.length > 0 && (
          <div>
            <div className="text-sm font-semibold text-gray-700 mb-2">Tips:</div>
            <ul className="space-y-2">
              {la_funding_explanation.tips.map((tip, idx) => (
                <li key={idx} className="flex items-start gap-2 text-sm text-gray-700">
                  <CheckCircle2 className="w-4 h-4 text-green-600 flex-shrink-0 mt-0.5" />
                  <span>{tip}</span>
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>

      {/* DPA Explanation */}
      <div className="bg-white rounded-lg p-6 border border-gray-200 shadow-sm">
        <h4 className="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
          <Home className="w-5 h-5 text-purple-600" />
          Deferred Payment Agreement (DPA)
        </h4>
        <p className="text-gray-700 mb-3">{dpa_explanation.what_it_means}</p>
        <p className="text-gray-700 mb-4 font-medium">{dpa_explanation.property_status}</p>
        
        {dpa_explanation.benefits && dpa_explanation.benefits.length > 0 && (
          <div className="mb-4">
            <div className="text-sm font-semibold text-gray-700 mb-2">Benefits:</div>
            <ul className="space-y-2">
              {dpa_explanation.benefits.map((benefit, idx) => (
                <li key={idx} className="flex items-start gap-2 text-sm text-gray-700">
                  <CheckCircle2 className="w-4 h-4 text-green-600 flex-shrink-0 mt-0.5" />
                  <span>{benefit}</span>
                </li>
              ))}
            </ul>
          </div>
        )}
        
        {dpa_explanation.considerations && dpa_explanation.considerations.length > 0 && (
          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
            <div className="text-sm font-semibold text-yellow-800 mb-2">Considerations:</div>
            <ul className="space-y-1">
              {dpa_explanation.considerations.map((consideration, idx) => (
                <li key={idx} className="text-sm text-yellow-700">• {consideration}</li>
              ))}
            </ul>
          </div>
        )}
      </div>

      {/* Expert Advice */}
      <div className="bg-white rounded-lg p-6 border border-gray-200 shadow-sm">
        <h4 className="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
          <FileText className="w-5 h-5 text-blue-600" />
          Expert Advice
        </h4>
        
        <div className="space-y-4">
          <div>
            <div className="text-sm font-semibold text-gray-700 mb-2">Funding Strategy:</div>
            <p className="text-gray-700">{expert_advice.funding_strategy}</p>
          </div>
          
          {expert_advice.maximizing_eligibility && expert_advice.maximizing_eligibility.length > 0 && (
            <div>
              <div className="text-sm font-semibold text-gray-700 mb-2">Maximizing Eligibility:</div>
              <ul className="space-y-2">
                {expert_advice.maximizing_eligibility.map((tip, idx) => (
                  <li key={idx} className="flex items-start gap-2 text-sm text-gray-700">
                    <TrendingUp className="w-4 h-4 text-green-600 flex-shrink-0 mt-0.5" />
                    <span>{tip}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
          
          {expert_advice.common_mistakes && expert_advice.common_mistakes.length > 0 && (
            <div className="bg-red-50 border border-red-200 rounded-lg p-4">
              <div className="text-sm font-semibold text-red-800 mb-2">Common Mistakes to Avoid:</div>
              <ul className="space-y-1">
                {expert_advice.common_mistakes.map((mistake, idx) => (
                  <li key={idx} className="text-sm text-red-700">• {mistake}</li>
                ))}
              </ul>
            </div>
          )}
          
          {expert_advice.when_to_reassess && (
            <div>
              <div className="text-sm font-semibold text-gray-700 mb-2 flex items-center gap-2">
                <Clock className="w-4 h-4" />
                When to Reassess:
              </div>
              <p className="text-sm text-gray-700">{expert_advice.when_to_reassess}</p>
            </div>
          )}
        </div>
      </div>

      {/* Actionable Next Steps */}
      {actionable_next_steps && actionable_next_steps.length > 0 && (
        <div className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-lg p-6 border border-blue-200">
          <h4 className="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
            <Target className="w-5 h-5 text-blue-600" />
            Your Action Plan
          </h4>
          <div className="space-y-3">
            {actionable_next_steps.map((step, idx) => (
              <div
                key={idx}
                className={`p-4 rounded-lg border ${getPriorityColor(step.priority)}`}
              >
                <div className="flex items-start justify-between mb-2">
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-semibold text-gray-700">Step {idx + 1}:</span>
                    <span className="text-sm font-semibold text-gray-900">{step.step}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className={`px-2 py-1 rounded text-xs font-medium ${getPriorityColor(step.priority)}`}>
                      {step.priority.toUpperCase()}
                    </span>
                    <span className="text-xs text-gray-600">{step.timeline}</span>
                  </div>
                </div>
                {step.details && (
                  <p className="text-sm text-gray-700 mt-2">{step.details}</p>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

