"""
LLM Insights Service for Free Report
Uses OpenAI GPT to generate expert explanations for why each care home matches the category
(Safe Bet, Best Value, Premium)
"""
import json
from typing import Dict, List, Any, Optional
from datetime import datetime
import httpx


class FreeReportLLMInsightsService:
    """Service to generate LLM-powered insights for free report care home matches"""
    
    def __init__(self, openai_api_key: Optional[str] = None):
        self.openai_api_key = openai_api_key
        self.base_url = "https://api.openai.com/v1"
        self.client = None
        if openai_api_key:
            try:
                self.client = httpx.AsyncClient(timeout=60.0)
                print("✅ OpenAI client initialized for free report insights")
            except Exception as e:
                print(f"⚠️ Failed to initialize OpenAI client: {e}")
    
    async def generate_home_insight(
        self,
        home_data: Dict[str, Any],
        match_type: str,
        user_context: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Generate LLM insight explanation for why a care home matches a specific category
        
        Args:
            home_data: Dictionary containing all home information from database and calculations
            match_type: Category - "Safe Bet", "Best Value", or "Premium"
            user_context: User's requirements (budget, care_type, postcode, etc.)
        
        Returns:
            Dictionary with:
            - home_name: Name of the care home
            - match_type: Category (Safe Bet/Best Value/Premium)
            - why_selected: 1-2 paragraph explanation (generated by LLM)
            - key_strengths: List of key strengths
            - considerations: List of considerations
        """
        if not self.client or not self.openai_api_key:
            return self._generate_fallback_insight(home_data, match_type, user_context)
        
        try:
            # Build prompt based on match type
            prompt = self._build_insight_prompt(home_data, match_type, user_context)
            
            headers = {
                "Authorization": f"Bearer {self.openai_api_key}",
                "Content-Type": "application/json"
            }
            
            payload = {
                "model": "gpt-4o-mini",  # Using gpt-4o-mini for cost efficiency
                "messages": [
                    {
                        "role": "system",
                        "content": self._get_system_prompt(match_type)
                    },
                    {
                        "role": "user",
                        "content": prompt
                    }
                ],
                "temperature": 0.7,
                "max_tokens": 800,  # Enough for 1-2 paragraphs
                "response_format": {"type": "json_object"}
            }
            
            response = await self.client.post(
                f"{self.base_url}/chat/completions",
                headers=headers,
                json=payload
            )
            response.raise_for_status()
            data = response.json()
            
            # Extract the response text
            response_text = data["choices"][0]["message"]["content"]
            
            # Parse JSON response
            try:
                insight_json = json.loads(response_text)
                
                # Ensure required fields
                result = {
                    "home_name": home_data.get('name', 'Unknown'),
                    "match_type": match_type,
                    "why_selected": insight_json.get("why_selected", ""),
                    "key_strengths": insight_json.get("key_strengths", []),
                    "considerations": insight_json.get("considerations", [])
                }
                
                # Validate why_selected is 1-2 paragraphs
                if not result["why_selected"] or len(result["why_selected"]) < 100:
                    # Fallback if response is too short
                    return self._generate_fallback_insight(home_data, match_type, user_context)
                
                return result
                
            except (json.JSONDecodeError, ValueError, KeyError) as e:
                print(f"⚠️ Error parsing OpenAI response: {e}")
                # Try to extract JSON from markdown code blocks
                import re
                json_match = re.search(r'```(?:json)?\s*(\{.*?\})\s*```', response_text, re.DOTALL)
                if json_match:
                    try:
                        insight_json = json.loads(json_match.group(1))
                        return {
                            "home_name": home_data.get('name', 'Unknown'),
                            "match_type": match_type,
                            "why_selected": insight_json.get("why_selected", ""),
                            "key_strengths": insight_json.get("key_strengths", []),
                            "considerations": insight_json.get("considerations", [])
                        }
                    except json.JSONDecodeError:
                        pass
                
                # Fallback if parsing fails
                return self._generate_fallback_insight(home_data, match_type, user_context)
                
        except httpx.HTTPStatusError as e:
            error_detail = f"HTTP {e.response.status_code}"
            if e.response.status_code == 401:
                error_detail += ": Invalid API key"
            elif e.response.status_code == 429:
                error_detail += ": Rate limit exceeded"
            elif e.response.status_code == 500:
                error_detail += ": OpenAI server error"
            
            print(f"⚠️ OpenAI API error: {error_detail}")
            return self._generate_fallback_insight(home_data, match_type, user_context)
        except Exception as e:
            print(f"⚠️ Error generating LLM insight: {e}")
            return self._generate_fallback_insight(home_data, match_type, user_context)
    
    def _get_system_prompt(self, match_type: str) -> str:
        """Get system prompt calibrated for the match type"""
        
        base_expertise = """You are a highly experienced specialist in UK care homes with 15 years of professional experience in matching care homes to clients' needs. 
You have deep expertise in:
- UK care home regulations and CQC inspection frameworks
- Care home quality assessment and due diligence
- Financial analysis of care home operations
- Client needs assessment and care matching
- Risk evaluation and safety protocols
- Value analysis and cost-benefit assessment

Your analysis should reflect the perspective of a seasoned professional who has successfully matched hundreds of clients with appropriate care homes over 15 years. 
Draw on your extensive experience to provide insights that go beyond surface-level data, identifying what truly matters for long-term care outcomes."""

        if match_type == "Safe Bet":
            return f"""{base_expertise}

Your task: Explain why this care home is the "Safe Bet" choice using ONLY the data provided from the database.

Use ALL available fields from the database to support your explanation. Cite specific data points:
- CQC Safe rating and other CQC sub-ratings
- FSA food hygiene rating
- Distance from user location
- Budget alignment (exact amounts)
- Facilities (wheelchair access, secure garden, etc.)
- Any other relevant fields from the database

IMPORTANT:
- Use ONLY data that exists in the provided database fields
- Do NOT suggest calling additional APIs or fetching missing data
- If a field is missing (e.g., no reviews), simply don't mention it - work with what's available
- Keep explanation to 1-2 paragraphs maximum
- Be specific with numbers, ratings, and distances from the database

Return ONLY valid JSON:
{{
  "why_selected": "1-2 paragraphs explaining why this is the Safe Bet, using specific data from database fields",
  "key_strengths": ["strength 1 with data", "strength 2 with data", "strength 3 with data"],
  "considerations": ["consideration 1", "consideration 2"]
}}"""
        
        elif match_type == "Best Value":
            return f"""{base_expertise}

Your task: Explain why this care home is the "Best Value" choice using ONLY the data provided from the database.

Use ALL available fields from the database to support your explanation. Calculate and cite specific value metrics:
- Exact savings: "£X/week saves £Y per year (£Z over 5 years)"
- Price comparison with budget
- Quality-to-price ratio using CQC ratings
- Included amenities and facilities from database
- Any pricing details (fee_residential_from, fee_nursing_from, etc.) if available

IMPORTANT:
- Use ONLY data that exists in the provided database fields
- Do NOT suggest calling additional APIs or fetching missing data
- If pricing details are missing, work with weekly_cost field
- Keep explanation to 1-2 paragraphs maximum
- Be specific with calculations using database numbers

Return ONLY valid JSON:
{{
  "why_selected": "1-2 paragraphs explaining why this is Best Value, with specific savings calculations using database fields",
  "key_strengths": ["value point 1 with numbers", "value point 2 with numbers", "value point 3 with numbers"],
  "considerations": ["consideration 1", "consideration 2"]
}}"""
        
        elif match_type == "Premium":
            return f"""{base_expertise}

Your task: Explain why this care home is the "Premium" choice using ONLY the data provided from the database.

Use ALL available fields from the database to support your explanation. Cite specific premium indicators:
- Outstanding CQC ratings (if available in database)
- Google reviews (if available in database - rating and count)
- Premium facilities (ensuite rooms, secure garden, WiFi, parking, etc.)
- Comprehensive care types
- FSA rating
- Any other premium features from database fields

IMPORTANT:
- Use ONLY data that exists in the provided database fields
- Do NOT suggest calling additional APIs or fetching missing data
- If reviews are not in database, don't mention them - work with what's available
- Keep explanation to 1-2 paragraphs maximum
- Be specific with ratings and features from database

Return ONLY valid JSON:
{{
  "why_selected": "1-2 paragraphs explaining why this is Premium, using specific premium indicators from database fields",
  "key_strengths": ["premium feature 1 with data", "premium feature 2 with data", "premium feature 3 with data"],
  "considerations": ["consideration 1", "consideration 2"]
}}"""
        
        else:
            return f"""{base_expertise}

Your task: Explain why this care home matches the "{match_type}" category using ONLY the data provided from the database.

Use ALL available fields from the database. Keep explanation to 1-2 paragraphs maximum.

IMPORTANT:
- Use ONLY data that exists in the provided database fields
- Do NOT suggest calling additional APIs
- Be specific with numbers and ratings from database

Return ONLY valid JSON:
{{
  "why_selected": "1-2 paragraphs explaining why this matches {match_type}, using database fields",
  "key_strengths": ["strength 1 with data", "strength 2 with data", "strength 3 with data"],
  "considerations": ["consideration 1", "consideration 2"]
}}"""
    
    def _build_insight_prompt(
        self,
        home_data: Dict[str, Any],
        match_type: str,
        user_context: Dict[str, Any]
    ) -> str:
        """Build detailed prompt with all available data"""
        
        # Extract home information
        name = home_data.get('name', 'Unknown')
        rating = home_data.get('rating') or home_data.get('cqc_rating') or home_data.get('cqc_rating_overall')
        weekly_cost = home_data.get('weekly_cost') or home_data.get('weeklyCost') or 0
        distance_km = home_data.get('distance_km') or home_data.get('distanceKm')
        care_types = home_data.get('care_types', []) or home_data.get('careTypes', [])
        fsa_rating = home_data.get('fsa_rating') or home_data.get('foodHygieneRating')
        beds_available = home_data.get('beds_available') or home_data.get('bedsAvailable')
        beds_total = home_data.get('beds_total') or home_data.get('bedsTotal')
        
        # CQC sub-ratings
        cqc_safe = home_data.get('cqc_rating_safe') or home_data.get('cqcSafeRating')
        cqc_caring = home_data.get('cqc_rating_caring') or home_data.get('cqcCaringRating')
        cqc_effective = home_data.get('cqc_rating_effective') or home_data.get('cqcEffectiveRating')
        cqc_responsive = home_data.get('cqc_rating_responsive') or home_data.get('cqcResponsiveRating')
        cqc_well_led = home_data.get('cqc_rating_well_led') or home_data.get('cqcWellLedRating')
        cqc_last_inspection_date = home_data.get('cqc_last_inspection_date') or home_data.get('cqcLastInspectionDate')
        
        # Google reviews
        google_rating = home_data.get('google_rating') or home_data.get('googleRating')
        review_count = home_data.get('review_count') or home_data.get('reviewCount')
        review_average_score = home_data.get('review_average_score') or home_data.get('reviewAverageScore')
        
        # Financial data (if available)
        financial_stability = home_data.get('financial_stability') or home_data.get('financialStability', {})
        financial_score = None
        if isinstance(financial_stability, dict):
            financial_score = financial_stability.get('altman_z_score') or financial_stability.get('risk_score')
        
        # Additional fields for Safe Bet analysis
        provider_name = home_data.get('provider_name') or home_data.get('providerName')
        brand_name = home_data.get('brand_name') or home_data.get('brandName')
        year_opened = home_data.get('year_opened') or home_data.get('yearOpened')
        year_registered = home_data.get('year_registered') or home_data.get('yearRegistered')
        accepts_nhs_chc = home_data.get('accepts_nhs_chc') or home_data.get('acceptsNhsChc')
        accepts_local_authority = home_data.get('accepts_local_authority') or home_data.get('acceptsLocalAuthority')
        has_nursing_care_license = home_data.get('has_nursing_care_license') or home_data.get('hasNursingCareLicense')
        has_personal_care_license = home_data.get('has_personal_care_license') or home_data.get('hasPersonalCareLicense')
        wheelchair_access = home_data.get('wheelchair_access') or home_data.get('wheelchairAccess')
        secure_garden = home_data.get('secure_garden') or home_data.get('secureGarden')
        
        # Additional fields for Best Value analysis
        fee_residential_from = home_data.get('fee_residential_from') or home_data.get('feeResidentialFrom')
        fee_nursing_from = home_data.get('fee_nursing_from') or home_data.get('feeNursingFrom')
        fee_dementia_from = home_data.get('fee_dementia_from') or home_data.get('feeDementiaFrom')
        fee_respite_from = home_data.get('fee_respite_from') or home_data.get('feeRespiteFrom')
        accepts_self_funding = home_data.get('accepts_self_funding') or home_data.get('acceptsSelfFunding')
        has_availability = home_data.get('has_availability') or home_data.get('hasAvailability')
        availability_status = home_data.get('availability_status') or home_data.get('availabilityStatus')
        wifi_available = home_data.get('wifi_available') or home_data.get('wifiAvailable')
        parking_onsite = home_data.get('parking_onsite') or home_data.get('parkingOnsite')
        
        # Additional fields for Premium analysis
        activities = home_data.get('activities') or {}
        media = home_data.get('media') or {}
        location_context = home_data.get('location_context') or home_data.get('locationContext')
        accreditations = home_data.get('accreditations')
        ensuite_rooms = home_data.get('ensuite_rooms') or home_data.get('ensuiteRooms')
        
        # User context
        budget = user_context.get('budget', 0)
        care_type = user_context.get('care_type', 'residential')
        postcode = user_context.get('postcode', '')
        local_authority = user_context.get('local_authority', '')
        
        # Calculate budget fit
        budget_diff = weekly_cost - budget if budget > 0 else 0
        budget_fit_percent = ((budget - abs(budget_diff)) / budget * 100) if budget > 0 else 0
        
        # Build prompt with ALL available database fields
        # Use ONLY data from database - no additional API calls
        prompt = f"""Analyze this UK care home using ONLY the data provided from the database and explain why it matches the "{match_type}" category.

CARE HOME DATA FROM DATABASE:
{json.dumps(home_data, indent=2, default=str)}

USER REQUIREMENTS:
- Budget: £{budget:,.0f} per week
- Required Care Type: {care_type}
- Postcode: {postcode}
- Budget Fit: £{abs(budget_diff):,.0f} {'over' if budget_diff > 0 else 'under'} budget ({budget_fit_percent:.1f}% fit)

YOUR TASK:
Write 1-2 paragraphs (maximum 2 paragraphs) explaining why this care home is the "{match_type}" choice.

CRITICAL REQUIREMENTS:
1. Use ONLY the data provided in the database fields above
2. Do NOT suggest calling additional APIs or fetching missing data
3. If a field is missing (e.g., no reviews in database), simply don't mention it - work with what's available
4. Be specific: cite exact numbers, ratings, distances, prices from the database
5. Keep it concise: maximum 2 paragraphs

For {match_type}, focus on:
- Safe Bet: CQC Safe rating, FSA rating, distance, budget alignment, facilities
- Best Value: Savings calculations, quality-to-price ratio, included amenities
- Premium: Outstanding ratings, premium features, comprehensive care types

Return ONLY valid JSON:
{{
  "why_selected": "1-2 paragraphs (max 2) explaining why this is {match_type}, using specific data from database",
  "key_strengths": ["strength 1 with data", "strength 2 with data", "strength 3 with data"],
  "considerations": ["consideration 1", "consideration 2"]
}}"""

        return prompt
    
    def _generate_fallback_insight(
        self,
        home_data: Dict[str, Any],
        match_type: str,
        user_context: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Generate fallback insight when OpenAI is unavailable - with specific data points"""
        
        name = home_data.get('name', 'Unknown')
        rating = home_data.get('rating') or home_data.get('cqc_rating') or 'Unknown'
        weekly_cost = home_data.get('weekly_cost') or 0
        distance_km = home_data.get('distance_km') or 0
        budget = user_context.get('budget', 0)
        
        # Extract specific data points
        cqc_safe = home_data.get('cqc_rating_safe') or home_data.get('cqcSafeRating')
        fsa_rating = home_data.get('fsa_rating') or home_data.get('foodHygieneRating')
        google_rating = home_data.get('google_rating') or home_data.get('googleRating')
        review_count = home_data.get('review_count') or home_data.get('reviewCount')
        care_types = home_data.get('care_types', []) or home_data.get('careTypes', [])
        
        if match_type == "Safe Bet":
            why_selected = f"{name} was selected as your Safe Bet because it demonstrates strong regulatory compliance. "
            
            # Specific CQC Safe rating
            if cqc_safe:
                why_selected += f"With a '{cqc_safe}' CQC Safe rating, this home has demonstrated robust safeguarding protocols, medication management, and protection from abuse - critical safety factors. "
            elif rating:
                why_selected += f"The '{rating}' CQC overall rating indicates reliable care standards and safety protocols. "
            
            # Specific FSA rating
            if fsa_rating:
                if fsa_rating >= 4:
                    why_selected += f"The {fsa_rating}-star Food Standards Agency rating confirms proper food safety protocols, essential for vulnerable residents. "
            
            # Specific budget alignment
            if weekly_cost and budget:
                budget_diff = weekly_cost - budget
                if abs(budget_diff) < 100:
                    why_selected += f"Priced at £{weekly_cost:,.0f}/week, it is £{abs(budget_diff):,.0f} within your £{budget:,.0f}/week budget, ensuring financial predictability and preventing future financial stress. "
            
            # Specific distance
            if distance_km and distance_km < 10:
                why_selected += f"Located {distance_km:.1f}km away, this proximity enables regular family oversight and quick response to any concerns - a key safety factor. "
            
            why_selected += "This combination of regulatory compliance, budget alignment, and accessibility makes it the safest and most reliable choice for your care needs."
        
        elif match_type == "Best Value":
            why_selected = f"{name} was selected as Best Value because it offers an excellent balance of quality and affordability. "
            
            # Specific quality rating
            if rating and ('good' in str(rating).lower() or 'outstanding' in str(rating).lower()):
                why_selected += f"With a '{rating}' CQC rating, it maintains high care standards. "
            
            # Specific savings calculation
            if weekly_cost and budget and weekly_cost < budget:
                savings_week = budget - weekly_cost
                savings_year = savings_week * 52
                savings_5year = savings_year * 5
                why_selected += f"At £{weekly_cost:,.0f}/week, it is £{savings_week:,.0f} below your £{budget:,.0f}/week budget, saving you £{savings_year:,.0f} per year (£{savings_5year:,.0f} over 5 years) without compromising essential care quality. "
            
            # Specific value proposition
            if rating and weekly_cost:
                why_selected += f"This represents exceptional value: you're receiving '{rating}' quality care at £{weekly_cost:,.0f}/week, typically available at higher price points. "
            
            why_selected += "This makes it the optimal choice for those seeking quality care at an affordable price point."
        
        elif match_type == "Premium":
            why_selected = f"{name} was selected as Premium because it represents the highest quality option available. "
            
            # Specific Outstanding ratings
            if rating and 'outstanding' in str(rating).lower():
                why_selected += f"With an 'Outstanding' CQC rating, this home ranks in the top 3% of UK care homes nationally, demonstrating exceptional care standards across all regulatory domains. "
            elif rating and 'good' in str(rating).lower():
                why_selected += f"With a 'Good' CQC rating, it maintains high quality care standards. "
            
            # Specific Google reviews
            if google_rating and google_rating >= 4.5:
                review_text = f"{google_rating}/5.0"
                if review_count:
                    review_text += f" from {review_count} reviews"
                why_selected += f"The {review_text} demonstrates exceptional resident and family satisfaction. "
            
            # Specific premium features
            if care_types and len(care_types) > 1:
                why_selected += f"Offering {', '.join(care_types)} care, this home provides comprehensive, specialized services. "
            
            # Specific FSA rating
            if fsa_rating == 5:
                why_selected += f"The 5-star Food Standards Agency rating indicates exceptional food quality and hygiene standards. "
            
            # Specific pricing justification
            if weekly_cost:
                why_selected += f"Priced at £{weekly_cost:,.0f}/week, this premium reflects the exceptional quality indicators and comprehensive services provided. "
            
            why_selected += "This home offers superior care delivery, comprehensive services, and exceptional quality indicators, making it the premium choice for those prioritizing the highest standard of care."
        
        else:
            why_selected = f"{name} was selected as {match_type} based on comprehensive analysis of quality, location, pricing, and care type availability."
        
        # Generate specific key strengths
        strengths = []
        if cqc_safe:
            strengths.append(f"CQC Safe rating: {cqc_safe} (safeguarding and protection)")
        elif rating and ('good' in str(rating).lower() or 'outstanding' in str(rating).lower()):
            strengths.append(f"CQC rating: {rating}")
        if fsa_rating and fsa_rating >= 4:
            strengths.append(f"FSA food hygiene: {fsa_rating}-star rating")
        if weekly_cost and budget:
            budget_diff = weekly_cost - budget
            if abs(budget_diff) < 100:
                strengths.append(f"Budget alignment: £{abs(budget_diff):,.0f} within budget")
            elif weekly_cost < budget:
                savings = budget - weekly_cost
                strengths.append(f"Cost savings: £{savings:,.0f}/week below budget")
        if distance_km and distance_km < 10:
            strengths.append(f"Proximity: {distance_km:.1f}km away (family oversight)")
        if google_rating and google_rating >= 4.5:
            review_text = f"{google_rating}/5.0 rating"
            if review_count:
                review_text += f" ({review_count} reviews)"
            strengths.append(f"Google reviews: {review_text}")
        
        # Generate considerations
        considerations = []
        if weekly_cost and budget and weekly_cost > budget + 100:
            considerations.append(f"Price is £{abs(weekly_cost - budget):,.0f} above your budget")
        if not rating:
            considerations.append("CQC rating information not available - verify during visit")
        if not cqc_safe:
            considerations.append("CQC Safe rating not available - verify safeguarding protocols during visit")
        
        return {
            "home_name": name,
            "match_type": match_type,
            "why_selected": why_selected,
            "key_strengths": strengths if strengths else ["Selected based on comprehensive data analysis"],
            "considerations": considerations
        }

