import React from 'react';
import { Lightbulb, AlertTriangle, TrendingUp, CheckCircle2, Clock, DollarSign, Target, Info } from 'lucide-react';
import type { ProfessionalReportData } from '../types';

interface LLMInsightsSectionProps {
  insights: NonNullable<ProfessionalReportData['llmInsights']>;
}

export default function LLMInsightsSection({ insights }: LLMInsightsSectionProps) {
  const { overall_explanation, top_home_analysis, expert_advice, actionable_next_steps } = insights.insights;

  const getConfidenceColor = (level: string) => {
    switch (level) {
      case 'high':
        return 'text-green-600 bg-green-50';
      case 'medium':
        return 'text-blue-600 bg-blue-50';
      default:
        return 'text-yellow-600 bg-yellow-50';
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'high':
        return 'text-red-600 bg-red-50 border-red-200';
      case 'medium':
        return 'text-yellow-600 bg-yellow-50 border-yellow-200';
      default:
        return 'text-blue-600 bg-blue-50 border-blue-200';
    }
  };

  return (
    <div className="mt-8 space-y-6">
      {/* Header */}
      <div className="bg-gradient-to-r from-purple-50 to-indigo-50 rounded-lg p-6 border border-purple-200">
        <div className="flex items-center gap-3 mb-2">
          <Lightbulb className="w-6 h-6 text-purple-600" />
          <h3 className="text-2xl font-bold text-gray-900">Expert Insights & Explanations</h3>
        </div>
        <p className="text-sm text-gray-600">
          AI-powered analysis by our care home placement specialist to help you understand your report
        </p>
        <div className="mt-3 flex items-center gap-2 text-xs text-gray-500">
          <Info className="w-4 h-4" />
          <span>Generated by {insights.model} • {new Date(insights.generated_at).toLocaleString()}</span>
        </div>
      </div>

      {/* Overall Explanation */}
      <div className="bg-white rounded-lg p-6 border border-gray-200 shadow-sm">
        <h4 className="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
          <Info className="w-5 h-5 text-blue-600" />
          What This Report Means for You
        </h4>
        <p className="text-gray-700 mb-4 leading-relaxed">{overall_explanation.summary}</p>
        
        <div className="mb-4">
          <div className="flex items-center gap-2 mb-2">
            <span className="text-sm font-semibold text-gray-700">Key Insights:</span>
            <span className={`px-2 py-1 rounded text-xs font-medium ${getConfidenceColor(overall_explanation.confidence_level)}`}>
              {overall_explanation.confidence_level.toUpperCase()} Confidence
            </span>
          </div>
          <ul className="space-y-2">
            {overall_explanation.key_insights.map((insight, idx) => (
              <li key={idx} className="flex items-start gap-2 text-gray-700">
                <CheckCircle2 className="w-4 h-4 text-green-600 flex-shrink-0 mt-0.5" />
                <span>{insight}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Top Home Analysis */}
      {top_home_analysis && top_home_analysis.length > 0 && (
        <div className="bg-white rounded-lg p-6 border border-gray-200 shadow-sm">
          <h4 className="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
            <Target className="w-5 h-5 text-green-600" />
            Why These Homes Were Recommended
          </h4>
          <div className="space-y-6">
            {top_home_analysis.map((home, idx) => (
              <div key={idx} className="border-l-4 border-green-500 pl-4 py-2">
                <div className="flex items-center gap-2 mb-2">
                  <span className="text-sm font-semibold text-gray-500">#{home.rank}</span>
                  <h5 className="text-md font-semibold text-gray-900">{home.home_name}</h5>
                </div>
                <p className="text-gray-700 mb-3">{home.why_recommended}</p>
                
                {home.match_score_explanation && (
                  <p className="text-sm text-gray-600 italic mb-3">{home.match_score_explanation}</p>
                )}
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <div className="text-sm font-semibold text-gray-700 mb-2">Key Strengths:</div>
                    <ul className="space-y-1">
                      {home.key_strengths.map((strength, sIdx) => (
                        <li key={sIdx} className="flex items-start gap-2 text-sm text-gray-600">
                          <TrendingUp className="w-4 h-4 text-green-600 flex-shrink-0 mt-0.5" />
                          <span>{strength}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                  
                  {home.considerations && home.considerations.length > 0 && (
                    <div>
                      <div className="text-sm font-semibold text-gray-700 mb-2">Things to Consider:</div>
                      <ul className="space-y-1">
                        {home.considerations.map((consideration, cIdx) => (
                          <li key={cIdx} className="flex items-start gap-2 text-sm text-gray-600">
                            <AlertTriangle className="w-4 h-4 text-yellow-600 flex-shrink-0 mt-0.5" />
                            <span>{consideration}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Expert Advice */}
      <div className="bg-white rounded-lg p-6 border border-gray-200 shadow-sm">
        <h4 className="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
          <DollarSign className="w-5 h-5 text-blue-600" />
          Expert Advice
        </h4>
        
        <div className="space-y-4">
          <div>
            <div className="text-sm font-semibold text-gray-700 mb-2">Funding Strategy:</div>
            <p className="text-gray-700">{expert_advice.funding_strategy}</p>
          </div>
          
          <div>
            <div className="text-sm font-semibold text-gray-700 mb-2 flex items-center gap-2">
              <Clock className="w-4 h-4" />
              Recommended Decision Timeline:
            </div>
            <p className="text-gray-700">{expert_advice.decision_timeline}</p>
          </div>
          
          {expert_advice.red_flags_to_watch && expert_advice.red_flags_to_watch.length > 0 && (
            <div>
              <div className="text-sm font-semibold text-gray-700 mb-2">Red Flags to Watch:</div>
              <ul className="space-y-2">
                {expert_advice.red_flags_to_watch.map((flag, idx) => (
                  <li key={idx} className="flex items-start gap-2 text-sm text-gray-700">
                    <AlertTriangle className="w-4 h-4 text-red-600 flex-shrink-0 mt-0.5" />
                    <span>{flag}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
          
          {expert_advice.negotiation_tips && expert_advice.negotiation_tips.length > 0 && (
            <div>
              <div className="text-sm font-semibold text-gray-700 mb-2">Negotiation Tips:</div>
              <ul className="space-y-2">
                {expert_advice.negotiation_tips.map((tip, idx) => (
                  <li key={idx} className="flex items-start gap-2 text-sm text-gray-700">
                    <CheckCircle2 className="w-4 h-4 text-blue-600 flex-shrink-0 mt-0.5" />
                    <span>{tip}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      </div>

      {/* Actionable Next Steps */}
      {actionable_next_steps && actionable_next_steps.length > 0 && (
        <div className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-lg p-6 border border-blue-200">
          <h4 className="text-lg font-semibold text-gray-900 mb-4 flex items-center gap-2">
            <Target className="w-5 h-5 text-blue-600" />
            Your Action Plan
          </h4>
          <div className="space-y-3">
            {actionable_next_steps.map((step, idx) => (
              <div
                key={idx}
                className={`p-4 rounded-lg border ${getPriorityColor(step.priority)}`}
              >
                <div className="flex items-start justify-between mb-2">
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-semibold text-gray-700">Step {idx + 1}:</span>
                    <span className="text-sm font-semibold text-gray-900">{step.step}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className={`px-2 py-1 rounded text-xs font-medium ${getPriorityColor(step.priority)}`}>
                      {step.priority.toUpperCase()}
                    </span>
                    <span className="text-xs text-gray-600">{step.timeline}</span>
                  </div>
                </div>
                {step.details && (
                  <p className="text-sm text-gray-700 mt-2">{step.details}</p>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

